#!/usr/bin/env bun
/**
 * Pre-compute the HTML export template assets at build time.
 * Reads template.html, template.css, template.js, and vendor scripts,
 * and exports them as TypeScript string constants so they can be bundled
 * into a compiled binary without filesystem access at runtime.
 */

const dir = new URL("../src/core/export-html/", import.meta.url).pathname;

const html = await Bun.file(`${dir}template.html`).text();
const css = await Bun.file(`${dir}template.css`).text();
const js = await Bun.file(`${dir}template.js`).text();
const markedJs = await Bun.file(`${dir}vendor/marked.min.js`).text();
const hljsJs = await Bun.file(`${dir}vendor/highlight.min.js`).text();

const output = `// Auto-generated by scripts/generate-template.ts - DO NOT EDIT
export const TEMPLATE_HTML = ${JSON.stringify(html)};
export const TEMPLATE_CSS = ${JSON.stringify(css)};
export const TEMPLATE_JS = ${JSON.stringify(js)};
export const MARKED_JS = ${JSON.stringify(markedJs)};
export const HLJS_JS = ${JSON.stringify(hljsJs)};
`;

await Bun.write(`${dir}template.generated.ts`, output);
console.log("Generated template.generated.ts");
