import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
	classifySemanticPath,
	collectSemanticCandidateFiles,
	discoverSemanticFiles,
} from "../src/extensions/daedalus/tools/semantic-file-discovery.js";

function rels(files: string[], root: string) {
	return files
		.map((file) =>
			file
				.slice(root.length + 1)
				.split("\\")
				.join("/"),
		)
		.sort();
}

describe("semantic file discovery", () => {
	let root: string;

	beforeEach(() => {
		root = join(tmpdir(), `daedalus-semantic-discovery-${Date.now()}-${Math.random().toString(36).slice(2)}`);
		mkdirSync(join(root, "src"), { recursive: true });
	});

	afterEach(() => rmSync(root, { recursive: true, force: true }));

	it("collects text source files through a dedicated discovery API", () => {
		writeFileSync(join(root, "src", "app.ts"), "export const app = true;\n");
		writeFileSync(join(root, "src", "image.png"), "not really an image\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/app.ts"]);
	});

	it("honors root and nested gitignore files", () => {
		writeFileSync(join(root, ".gitignore"), "ignored-root/\n*.local.ts\n*.ignored.ts\n");
		mkdirSync(join(root, "ignored-root"), { recursive: true });
		writeFileSync(join(root, "ignored-root", "x.ts"), "export const x = true;\n");
		writeFileSync(join(root, "src", "kept.ts"), "export const kept = true;\n");
		writeFileSync(join(root, "src", "secret.local.ts"), "export const secret = true;\n");
		writeFileSync(join(root, "src", ".gitignore"), "nested-ignored.ts\n!keep.ignored.ts\n");
		writeFileSync(join(root, "src", "nested-ignored.ts"), "export const ignored = true;\n");
		writeFileSync(join(root, "src", "drop.ignored.ts"), "export const drop = true;\n");
		writeFileSync(join(root, "src", "keep.ignored.ts"), "export const keep = true;\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/keep.ignored.ts", "src/kept.ts"]);
	});

	it("does not globally exclude source packages named agent", () => {
		mkdirSync(join(root, "packages", "agent", "src"), { recursive: true });
		writeFileSync(join(root, "packages", "agent", "src", "agent.ts"), "export const agent = true;\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["packages/agent/src/agent.ts"]);
	});

	it("prunes hard-excluded directories before nested ignore files can re-include them", () => {
		mkdirSync(join(root, "node_modules", "dep"), { recursive: true });
		writeFileSync(join(root, "node_modules", ".semanticignore"), "!dep/index.ts\n");
		writeFileSync(join(root, "node_modules", "dep", "index.ts"), "export const dep = true;\n");
		writeFileSync(join(root, "src", "app.ts"), "export const app = true;\n");

		const result = discoverSemanticFiles(root, { profile: "exhaustive" });
		expect(rels(result.files, root)).toEqual(["src/app.ts"]);
		expect(result.skippedByReason.hardExclude).toBeGreaterThanOrEqual(1);
	});

	it("honors root and nested semanticignore files", () => {
		writeFileSync(join(root, ".semanticignore"), "benchmarks/\n*.fixture.json\n");
		mkdirSync(join(root, "benchmarks"), { recursive: true });
		writeFileSync(join(root, "benchmarks", "task.py"), "print('ignored')\n");
		writeFileSync(join(root, "src", "kept.ts"), "export const kept = true;\n");
		writeFileSync(join(root, "src", "data.fixture.json"), '{"fixture":true}\n');

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/kept.ts"]);
	});

	it("skips generated files by path and header marker", () => {
		mkdirSync(join(root, "src", "__generated__"), { recursive: true });
		writeFileSync(join(root, "src", "__generated__", "client.ts"), "export const client = true;\n");
		writeFileSync(join(root, "src", "api.pb.go"), "package api\n");
		writeFileSync(
			join(root, "src", "marker.ts"),
			"// Code generated by protoc. DO NOT EDIT.\nexport const marker = true;\n",
		);
		writeFileSync(join(root, "src", "handwritten.ts"), "export const handwritten = true;\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/handwritten.ts"]);
	});

	it("skips dependency lockfiles and machine manifests", () => {
		const lockfiles = [
			"composer.lock",
			"Gemfile.lock",
			"poetry.lock",
			"uv.lock",
			"Pipfile.lock",
			"go.sum",
			"deno.lock",
		];
		for (const file of lockfiles) writeFileSync(join(root, file), "lock data\n");
		writeFileSync(join(root, "src", "kept.ts"), "export const kept = true;\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/kept.ts"]);
	});

	it("skips snapshots golden outputs recordings and traces", () => {
		const dirs = ["__snapshots__", "snapshots", "golden", "goldens", "recordings", "cassettes", "traces"];
		for (const dir of dirs) {
			mkdirSync(join(root, dir), { recursive: true });
			writeFileSync(join(root, dir, "artifact.json"), '{"artifact":true}\n');
		}
		writeFileSync(join(root, "src", "kept.ts"), "export const kept = true;\n");
		writeFileSync(join(root, "src", "component.snap"), "snapshot text\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/kept.ts"]);
	});

	it("skips minified and bundled text files", () => {
		writeFileSync(join(root, "src", "vendor.min.js"), "var a=1;".repeat(500));
		writeFileSync(join(root, "src", "app.bundle.js"), "var b=2;".repeat(500));
		writeFileSync(join(root, "src", "longline.js"), `${"x".repeat(5000)}\n`);
		writeFileSync(join(root, "src", "app.ts"), "export const app = true;\n");

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/app.ts"]);
	});

	it("uses stricter size caps for data-like text files", () => {
		writeFileSync(join(root, "src", "large-source.ts"), `export const text = \`${"a".repeat(150_000)}\`;\n`);
		writeFileSync(join(root, "src", "large-data.json"), `{"data":"${"a".repeat(150_000)}"}\n`);
		writeFileSync(join(root, "src", "events.jsonl"), `${'{"x":1}\n'.repeat(20_000)}`);

		expect(rels(collectSemanticCandidateFiles(root), root)).toEqual(["src/large-source.ts"]);
	});

	it("classifies semantic path value", () => {
		expect(classifySemanticPath("packages/coding-agent/src/core/agent-session.ts")).toBe("high");
		expect(classifySemanticPath("packages/coding-agent/test/semantic.test.ts")).toBe("medium");
		expect(classifySemanticPath("fixtures/sample.json")).toBe("low");
	});

	it("supports minimal normal broad and exhaustive profiles", () => {
		writeFileSync(join(root, "src", "app.ts"), "export const app = true;\n");
		mkdirSync(join(root, "tests"), { recursive: true });
		writeFileSync(join(root, "tests", "app.test.ts"), "test('app', () => {});\n");
		mkdirSync(join(root, "fixtures"), { recursive: true });
		writeFileSync(join(root, "fixtures", "tiny.json"), '{"fixture":true}\n');

		expect(rels(collectSemanticCandidateFiles(root, { profile: "minimal" }), root)).toEqual(["src/app.ts"]);
		expect(rels(collectSemanticCandidateFiles(root, { profile: "normal" }), root)).toEqual([
			"src/app.ts",
			"tests/app.test.ts",
		]);
		expect(rels(collectSemanticCandidateFiles(root, { profile: "broad" }), root)).toEqual([
			"fixtures/tiny.json",
			"src/app.ts",
			"tests/app.test.ts",
		]);
		expect(rels(collectSemanticCandidateFiles(root, { profile: "exhaustive" }), root)).toEqual([
			"fixtures/tiny.json",
			"src/app.ts",
			"tests/app.test.ts",
		]);
	});

	it("reports skip telemetry by reason", () => {
		writeFileSync(join(root, "src", "app.ts"), "export const app = true;\n");
		mkdirSync(join(root, "dist"), { recursive: true });
		writeFileSync(join(root, "dist", "bundle.js"), "export const bundle = true;\n");
		writeFileSync(join(root, "package-lock.json"), "{}\n");

		const result = discoverSemanticFiles(root);
		expect(rels(result.files, root)).toEqual(["src/app.ts"]);
		expect(result.skippedByReason.hardExclude).toBeGreaterThanOrEqual(1);
		expect(result.skippedByReason.lockfile).toBeGreaterThanOrEqual(1);
	});
});
