import { type Dirent, existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import path from "node:path";
import ignore, { type Ignore } from "ignore";
import { minimatch } from "minimatch";
import { discoverFdDefault } from "./fd-default.js";
import { filterAndResolve, isIgnoredByName } from "./file-discovery-filters.js";
import { DEFAULT_SEMANTIC_INDEX_PROFILE, type SemanticIndexProfile } from "./semantic-config.js";
import type { SemanticPathValue, SemanticSkipCounts, SemanticSkipReason } from "./semantic-types.js";

export const SEMANTIC_TEXT_EXTENSIONS = new Set([
	".ts",
	".tsx",
	".js",
	".jsx",
	".json",
	".jsonl",
	".md",
	".txt",
	".py",
	".rs",
	".go",
	".java",
	".c",
	".cc",
	".cpp",
	".h",
	".hpp",
	".yaml",
	".yml",
	".toml",
	".sh",
	".css",
	".html",
	".csv",
	".log",
	".gitignore",
	".semanticignore",
]);

const LOCKFILE_GLOBS = [
	"**/package-lock.json",
	"**/npm-shrinkwrap.json",
	"**/yarn.lock",
	"**/pnpm-lock.yaml",
	"**/bun.lock",
	"**/Cargo.lock",
	"**/composer.lock",
	"**/Gemfile.lock",
	"**/poetry.lock",
	"**/uv.lock",
	"**/Pipfile.lock",
	"**/go.sum",
	"**/deno.lock",
];

const HARD_EXCLUDED_DIR_NAMES = new Set([
	"node_modules",
	"bower_components",
	".git",
	".hg",
	".svn",
	".daedalus",
	".venv",
	"venv",
	"env",
	".env",
	"site-packages",
	"site_packages",
	"__pycache__",
	".pytest_cache",
	".mypy_cache",
	".ruff_cache",
	".cache",
	"cache",
	".tmp",
	"tmp",
	"temp",
	"dist",
	"dist-chrome",
	"dist-firefox",
	"build",
	"target",
	"out",
	"coverage",
	".nyc_output",
	".next",
	".nuxt",
	".svelte-kit",
	".turbo",
	".parcel-cache",
	".npm",
	".yarn",
	".pnpm-store",
	"generated",
	"__generated__",
	"__snapshots__",
	"snapshots",
	"snapshot",
	"golden",
	"goldens",
	"recordings",
	"cassettes",
	"traces",
]);

const HARD_EXCLUDED_PATH_PREFIXES = ["testing/harbor", "testing/terminal-bench-2", "testing/results"];

const HARD_EXCLUDED_FILE_GLOBS = [
	"**/*.tsbuildinfo",
	"**/*.generated.*",
	"**/*.gen.*",
	"**/*.pb.*",
	"**/*.snap",
	"**/*.har",
	"**/*.min.js",
	"**/*.min.css",
	"**/*.bundle.js",
	"**/bundle.*",
	"**/vendor.*",
];

export const SEMANTIC_HARD_EXCLUDE_GLOBS = [
	...Array.from(HARD_EXCLUDED_DIR_NAMES, (name) => `**/${name}/**`),
	...HARD_EXCLUDED_PATH_PREFIXES.map((prefix) => `${prefix}/**`),
	...HARD_EXCLUDED_FILE_GLOBS,
	...LOCKFILE_GLOBS,
];

const GENERATED_MARKERS = [
	"@generated",
	"code generated by",
	"do not edit",
	"automatically generated",
	"this file was generated",
];
const DEFAULT_SOURCE_SIZE_LIMIT = 200_000;
const DEFAULT_DOC_SIZE_LIMIT = 300_000;
const DEFAULT_DATA_SIZE_LIMIT = 100_000;

interface IgnoreMatcher {
	kind: "gitignore" | "semanticignore";
	baseDir: string;
	matcher: Ignore;
}

export interface SemanticFileDiscoveryOptions {
	profile?: SemanticIndexProfile;
	skipContentHeuristics?: boolean;
}

export interface SemanticDiscoveryResult {
	files: string[];
	skippedByReason: SemanticSkipCounts;
}

function toPosix(value: string): string {
	return value.split(path.sep).join("/");
}

function increment(counts: SemanticSkipCounts, reason: SemanticSkipReason): void {
	counts[reason] = (counts[reason] ?? 0) + 1;
}

function matchesGlob(relativePath: string, globs: string[]): boolean {
	return globs.some((glob) => minimatch(relativePath, glob, { dot: true, nocase: false, matchBase: false }));
}

function loadIgnoreMatcher(dir: string, ignoreFileName: ".gitignore" | ".semanticignore"): IgnoreMatcher | undefined {
	const filePath = path.join(dir, ignoreFileName);
	if (!existsSync(filePath)) return undefined;
	return {
		kind: ignoreFileName === ".gitignore" ? "gitignore" : "semanticignore",
		baseDir: dir,
		matcher: ignore().add(readFileSync(filePath, "utf8")),
	};
}

function withDirectoryIgnoreMatchers(dir: string, inherited: IgnoreMatcher[]): IgnoreMatcher[] {
	const next = [...inherited];
	const gitignore = loadIgnoreMatcher(dir, ".gitignore");
	if (gitignore) next.push(gitignore);
	const semanticignore = loadIgnoreMatcher(dir, ".semanticignore");
	if (semanticignore) next.push(semanticignore);
	return next;
}

function ignoreReason(
	filePath: string,
	isDirectory: boolean,
	matchers: IgnoreMatcher[],
): SemanticSkipReason | undefined {
	let ignoredBy: SemanticSkipReason | undefined;
	for (const matcher of matchers) {
		const relative = toPosix(path.relative(matcher.baseDir, filePath));
		if (relative === "" || relative.startsWith("../")) continue;
		const result = matcher.matcher.test(isDirectory ? `${relative}/` : relative);
		if (result.ignored) ignoredBy = matcher.kind;
		if (result.unignored) ignoredBy = undefined;
	}
	return ignoredBy;
}

export function isSemanticTextFile(filePath: string): boolean {
	const ext = path.extname(filePath).toLowerCase();
	const base = path.basename(filePath).toLowerCase();
	return SEMANTIC_TEXT_EXTENSIONS.has(ext) || SEMANTIC_TEXT_EXTENSIONS.has(base) || ext === "";
}

function hasGeneratedHeader(filePath: string): boolean {
	try {
		const header = readFileSync(filePath, "utf8").slice(0, 2048).toLowerCase();
		return GENERATED_MARKERS.some((marker) => header.includes(marker));
	} catch {
		return false;
	}
}

function looksMinified(filePath: string): boolean {
	const ext = path.extname(filePath).toLowerCase();
	if (![".js", ".jsx", ".css", ".html", ".json", ".jsonl", ".csv"].includes(ext)) return false;
	try {
		const sample = readFileSync(filePath, "utf8").slice(0, 8192);
		const lines = sample.split(/\r?\n/);
		const longestLine = Math.max(...lines.map((line) => line.length));
		const averageLine = sample.length / Math.max(lines.length, 1);
		return longestLine > 2000 || averageLine > 500;
	} catch {
		return false;
	}
}

export function semanticContentSkipReason(filePath: string): SemanticSkipReason | undefined {
	if (hasGeneratedHeader(filePath)) return "generated";
	if (looksMinified(filePath)) return "minified";
	return undefined;
}

export function semanticSizeLimit(filePath: string): number {
	const ext = path.extname(filePath).toLowerCase();
	if ([".json", ".jsonl", ".csv", ".log"].includes(ext)) return DEFAULT_DATA_SIZE_LIMIT;
	if ([".md", ".txt"].includes(ext)) return DEFAULT_DOC_SIZE_LIMIT;
	return DEFAULT_SOURCE_SIZE_LIMIT;
}

export function isWithinSemanticSizeLimit(filePath: string): boolean {
	try {
		return statSync(filePath).size <= semanticSizeLimit(filePath);
	} catch {
		return false;
	}
}

export function classifySemanticPath(relativePath: string): SemanticPathValue {
	const normalized = relativePath.split("\\").join("/");
	if (/^(packages\/[^/]+\/src\/|src\/|lib\/)/.test(normalized)) return "high";
	if (/^(packages\/[^/]+\/test\/|test\/|tests\/|docs\/|\.github\/)/.test(normalized)) return "medium";
	if (/(fixture|fixtures|sample|mock|mocks)/i.test(normalized)) return "low";
	return "medium";
}

function includeByProfile(value: SemanticPathValue, profile: SemanticIndexProfile): boolean {
	if (profile === "exhaustive") return true;
	if (profile === "broad") return true;
	if (profile === "normal") return value !== "low";
	return value === "high";
}

function hardExcludeReason(
	relativePath: string,
	baseName: string,
	isDirectory: boolean,
): SemanticSkipReason | undefined {
	if (!isDirectory && matchesGlob(relativePath, LOCKFILE_GLOBS)) return "lockfile";
	if (isDirectory && HARD_EXCLUDED_DIR_NAMES.has(baseName)) return "hardExclude";
	if (
		!isDirectory &&
		relativePath
			.split("/")
			.slice(0, -1)
			.some((segment) => HARD_EXCLUDED_DIR_NAMES.has(segment))
	)
		return "hardExclude";
	if (HARD_EXCLUDED_PATH_PREFIXES.some((prefix) => relativePath === prefix || relativePath.startsWith(`${prefix}/`)))
		return "hardExclude";
	if (!isDirectory && matchesGlob(relativePath, HARD_EXCLUDED_FILE_GLOBS)) return "hardExclude";
	return undefined;
}

function candidateIgnoreReason(cwd: string, absolutePath: string): SemanticSkipReason | undefined {
	const parent = path.dirname(absolutePath);
	const dirs: string[] = [];
	let current = path.resolve(cwd);
	const resolvedParent = path.resolve(parent);
	while (current === resolvedParent || resolvedParent.startsWith(`${current}${path.sep}`)) {
		dirs.push(current);
		if (current === resolvedParent) break;
		const relative = path.relative(current, resolvedParent).split(path.sep)[0];
		current = path.join(current, relative);
	}
	let matchers: IgnoreMatcher[] = [];
	for (const dir of dirs) matchers = withDirectoryIgnoreMatchers(dir, matchers);
	return ignoreReason(absolutePath, false, matchers);
}

export function discoverSemanticFiles(
	cwd: string,
	options: SemanticFileDiscoveryOptions = {},
): SemanticDiscoveryResult {
	const profile = options.profile ?? DEFAULT_SEMANTIC_INDEX_PROFILE;
	const useContentHeuristics = options.skipContentHeuristics !== true;
	const skippedByReason: SemanticSkipCounts = {};
	const files: string[] = [];
	const visit = (dir: string, inheritedMatchers: IgnoreMatcher[]): void => {
		const matchers = withDirectoryIgnoreMatchers(dir, inheritedMatchers);
		let entries: Dirent[];
		try {
			entries = readdirSync(dir, { withFileTypes: true });
		} catch {
			return;
		}
		for (const entry of entries) {
			const absolutePath = path.join(dir, entry.name);
			const relativePath = toPosix(path.relative(cwd, absolutePath));
			const isDirectory = entry.isDirectory();
			const hardReason = hardExcludeReason(relativePath, entry.name, isDirectory);
			if (hardReason) {
				increment(skippedByReason, hardReason);
				continue;
			}
			const ignored = ignoreReason(absolutePath, isDirectory, matchers);
			if (ignored) {
				increment(skippedByReason, ignored);
				continue;
			}
			if (isDirectory) {
				visit(absolutePath, matchers);
				continue;
			}
			if (!entry.isFile()) continue;
			if (!isSemanticTextFile(absolutePath)) {
				increment(skippedByReason, "nonText");
				continue;
			}
			if (!isWithinSemanticSizeLimit(absolutePath)) {
				increment(skippedByReason, "sizeLimit");
				continue;
			}
			const contentSkipReason = useContentHeuristics ? semanticContentSkipReason(absolutePath) : undefined;
			if (contentSkipReason) {
				increment(skippedByReason, contentSkipReason);
				continue;
			}
			if (!includeByProfile(classifySemanticPath(relativePath), profile)) {
				increment(skippedByReason, "profile");
				continue;
			}
			files.push(absolutePath);
		}
	};
	visit(cwd, []);
	return { files: files.sort((a, b) => a.localeCompare(b)), skippedByReason };
}

function applySemanticCandidatePolicy(
	cwd: string,
	candidateFiles: string[],
	options: SemanticFileDiscoveryOptions = {},
): SemanticDiscoveryResult {
	const profile = options.profile ?? DEFAULT_SEMANTIC_INDEX_PROFILE;
	const useContentHeuristics = options.skipContentHeuristics !== true;
	const skippedByReason: SemanticSkipCounts = {};
	const files: string[] = [];
	for (const absolutePath of candidateFiles) {
		const relativePath = toPosix(path.relative(cwd, absolutePath));
		const baseName = path.basename(absolutePath);
		if (relativePath === "" || relativePath.startsWith("../")) {
			increment(skippedByReason, "hardExclude");
			continue;
		}
		const hardReason = hardExcludeReason(relativePath, baseName, false);
		if (hardReason) {
			increment(skippedByReason, hardReason);
			continue;
		}
		const ignored = candidateIgnoreReason(cwd, absolutePath);
		if (ignored) {
			increment(skippedByReason, ignored);
			continue;
		}
		if (isIgnoredByName(absolutePath)) {
			increment(skippedByReason, "lockfile");
			continue;
		}
		if (!isWithinSemanticSizeLimit(absolutePath)) {
			increment(skippedByReason, "sizeLimit");
			continue;
		}
		const contentSkipReason = useContentHeuristics ? semanticContentSkipReason(absolutePath) : undefined;
		if (contentSkipReason) {
			increment(skippedByReason, contentSkipReason);
			continue;
		}
		if (!includeByProfile(classifySemanticPath(relativePath), profile)) {
			increment(skippedByReason, "profile");
			continue;
		}
		files.push(path.resolve(absolutePath));
	}
	return { files: files.sort((a, b) => a.localeCompare(b)), skippedByReason };
}

export async function discoverSemanticFilesFdDefault(
	cwd: string,
	options: SemanticFileDiscoveryOptions = {},
): Promise<SemanticDiscoveryResult> {
	const rawFiles = await discoverFdDefault(cwd);
	const forgeFiltered = filterAndResolve(cwd, rawFiles);
	return applySemanticCandidatePolicy(cwd, forgeFiltered, options);
}

async function collectSemanticCandidateFilesAsync(
	cwd: string,
	options: SemanticFileDiscoveryOptions = {},
): Promise<string[]> {
	return (await discoverSemanticFilesFdDefault(cwd, options)).files;
}

export function collectSemanticCandidateFiles(cwd: string, options: SemanticFileDiscoveryOptions = {}): string[] {
	const syncCandidates = Bun.spawnSync(
		[
			"bun",
			"--eval",
			`
		import { discoverSemanticFilesFdDefault } from ${JSON.stringify(import.meta.url)};
		const result = await discoverSemanticFilesFdDefault(${JSON.stringify(cwd)}, ${JSON.stringify(options)});
		process.stdout.write(JSON.stringify(result.files));
	`,
		],
		{ stdout: "pipe", stderr: "pipe" },
	);
	if (syncCandidates.exitCode === 0) {
		try {
			return JSON.parse(new TextDecoder().decode(syncCandidates.stdout)) as string[];
		} catch {
			// fall through to the in-process equivalent below
		}
	}
	// Synchronous fallback for callers that cannot await: mirror FdDefault's
	// git-first-then-walker policy before applying the same Forge filters.
	const git = Bun.spawnSync(["git", "ls-files", "--full-name", "--cached", "--others", "--exclude-standard"], {
		cwd,
		stdout: "pipe",
		stderr: "pipe",
	});
	if (git.exitCode === 0) {
		const root = Bun.spawnSync(["git", "rev-parse", "--show-toplevel"], { cwd, stdout: "pipe", stderr: "pipe" });
		if (root.exitCode === 0) {
			const repoRoot = path.resolve(new TextDecoder().decode(root.stdout).trim().split(/\r?\n/)[0]);
			const rawFiles = new TextDecoder()
				.decode(git.stdout)
				.split(/\r?\n/)
				.map((line) => line.trim())
				.filter(Boolean)
				.map((file) => path.resolve(repoRoot, file));
			if (rawFiles.length > 0)
				return applySemanticCandidatePolicy(cwd, filterAndResolve(cwd, rawFiles), options).files;
		}
	}
	return discoverSemanticFiles(cwd, options).files;
}

export { collectSemanticCandidateFilesAsync };
